name: native_doctor
description: A tool that analyzes Flutter and Dart project dependencies, find requirements for native toolchains and, if possible, resolves issues.
version: 0.1.0-dev.4
repository: https://github.com/irondash/native_toolchain_rust

environment:
  sdk: ^3.4.0-265.0.dev

executables:
  native_doctor:

# Add regular dependencies here.
dependencies:
  native_toolchain_rust_common: ^0.1.0-dev.3
  args: ^2.4.2
  package_config: ^2.1.0
  rustup: ^0.1.0-dev.3
  pub_semver: ^2.1.4
  yaml: ^3.1.2
  pubspec_parse: ^1.2.3
  native_assets_cli: ^0.7.2
  collection: ^1.18.0
  logging: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.4
